// Gates include/runtime/fp16.hpp; the shared IEEE binary16 conversions.
//
//   ./metal_fp16_test [vals.txt expect.txt]
//
// Self-contained: the structured cases and the exhaustive round trip need no data files. If a
// fixture pair IS given (~/models/f16_vals.txt + f16_expect.txt, one float and one expected
// uint16 per line, generated by numpy's astype(float16)), it is checked too.
//
// every check here is paired with a control: the previous hand-rolled converter; which
// truncated the mantissa and flushed subnormals to zero; is compiled in as `legacy_*` and must
// FAIL the same check. Four checks in this project's history passed while measuring nothing, so
// a check that cannot be seen failing is not evidence. If a control ever stops failing, the check
// it guards has gone blind and the test says so.

#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
#include <vector>

#include "runtime/fp16.hpp"

namespace {

int failures = 0;

void report(const char* name, bool ok, const char* detail = "") {
  std::printf("  %-28s %s%s%s\n", name, ok ? "PASS" : "FAIL", *detail ? "  " : "", detail);
  if (!ok) ++failures;
}

// ---- control: the converter this replaced, verbatim ----
std::uint16_t legacy_f32_to_f16(float f) {
  std::uint32_t x;
  std::memcpy(&x, &f, 4);
  const std::uint32_t sign = (x >> 16) & 0x8000u;
  const std::int32_t exp = static_cast<std::int32_t>((x >> 23) & 0xFFu) - 127 + 15;
  const std::uint32_t man = x & 0x7FFFFFu;
  if (exp <= 0) return static_cast<std::uint16_t>(sign);
  if (exp >= 31) return static_cast<std::uint16_t>(sign | 0x7C00u);
  return static_cast<std::uint16_t>(sign | (static_cast<std::uint32_t>(exp) << 10) | (man >> 13));
}
float legacy_f16_to_f32(std::uint16_t h) {
  const std::uint32_t sign = (h & 0x8000u) << 16;
  const std::uint32_t exp = (h >> 10) & 0x1Fu;
  const std::uint32_t man = h & 0x3FFu;
  std::uint32_t out;
  if (exp == 0) {
    out = sign;
  } else if (exp == 31) {
    out = sign | 0x7F800000u | (man << 13);
  } else {
    out = sign | ((exp - 15 + 127) << 23) | (man << 13);
  }
  float f;
  std::memcpy(&f, &out, 4);
  return f;
}

struct Case {
  float in;
  std::uint16_t want;
  const char* why;
};

// Hand-computed, not generated by the code under test; an expectation derived the same way the
// implementation derives it only proves the implementation is self-consistent.
const Case kCases[] = {
    {0.0f, 0x0000, "zero"},
    {-0.0f, 0x8000, "negative zero"},
    {1.0f, 0x3C00, "one"},
    {-2.0f, 0xC000, "minus two"},
    {65504.0f, 0x7BFF, "largest finite fp16"},
    {65519.0f, 0x7BFF, "just below the inf midpoint, rounds down"},
    {65520.0f, 0x7C00, "midpoint 65520 rounds to INF, not 65504"},
    {131008.0f, 0x7C00, "overflow to inf"},
    {-131008.0f, 0xFC00, "negative overflow"},
    {6.103515625e-05f, 0x0400, "smallest normal 2^-14"},
    {6.0975552e-05f, 0x03FF, "largest subnormal"},
    {5.9604644775390625e-08f, 0x0001, "smallest subnormal 2^-24"},
    {2.98023223876953125e-08f, 0x0000, "2^-25 is a tie, rounds to even = 0"},
    {8.940696716308594e-08f, 0x0002, "1.5 * 2^-24, tie rounds to even = 2"},
    {-5.9604644775390625e-08f, 0x8001, "negative smallest subnormal"},
    {1.0e-10f, 0x0000, "far underflow"},
    {-0.193464786f, 0xB231, "round to nearest, not truncate (truncating gives 0xB230)"},
    // The fp16 ULP at 1.0 is 2^-10 == 0.0009765625, so these step in whole and half ULPs.
    {1.0009765625f, 0x3C01, "1 + 1 ULP, exactly representable"},
    {1.00048828125f, 0x3C00, "tie at 1 + 0.5 ULP rounds to even, down to 0x3C00"},
    {1.0014648437f, 0x3C02, "tie at 1 + 1.5 ULP rounds to even, up to 0x3C02"},
    {1.001708984375f, 0x3C02, "1 + 1.75 ULP rounds up"},
    {1.0006103515625f, 0x3C01, "1 + 0.625 ULP rounds up"},
};

}  // namespace

int main(int argc, char** argv) {
  std::setvbuf(stdout, nullptr, _IONBF, 0);
  std::printf("[metal_fp16] IEEE binary16 conversions (include/runtime/fp16.hpp)\n");

  // ---- structured cases ----
  {
    int bad = 0, legacy_bad = 0;
    for (const Case& c : kCases) {
      const std::uint16_t got = cpi::f32_to_f16(c.in);
      if (got != c.want) {
        std::printf("      %-52s got=0x%04X want=0x%04X\n", c.why, got, c.want);
        ++bad;
      }
      if (legacy_f32_to_f16(c.in) != c.want) ++legacy_bad;
    }
    char d[96];
    std::snprintf(d, sizeof d, "%d/%zu wrong", bad, sizeof(kCases) / sizeof(kCases[0]));
    report("f32_to_f16 structured", bad == 0, d);
    std::snprintf(d, sizeof d, "legacy fails %d of them, as it must", legacy_bad);
    report("  control: legacy differs", legacy_bad > 0, d);
  }

  // ---- exhaustive: every fp16 bit pattern must survive f16 -> f32 -> f16 ----
  //
  // NaN is excluded: the payload is deliberately not preserved through the narrowing direction.
  {
    int bad = 0, legacy_bad = 0;
    std::uint16_t first_bad = 0;
    for (std::uint32_t b = 0; b < 0x10000u; ++b) {
      const std::uint16_t h = static_cast<std::uint16_t>(b);
      const bool is_nan = ((h >> 10) & 0x1Fu) == 0x1Fu && (h & 0x3FFu) != 0u;
      if (is_nan) continue;
      if (cpi::f32_to_f16(cpi::f16_to_f32(h)) != h) {
        if (bad == 0) first_bad = h;
        ++bad;
      }
      if (legacy_f32_to_f16(legacy_f16_to_f32(h)) != h) ++legacy_bad;
    }
    char d[128];
    std::snprintf(d, sizeof d, "%d/65024 patterns lost%s", bad, bad ? " (first 0x" : "");
    if (bad) std::snprintf(d, sizeof d, "%d patterns lost, first 0x%04X", bad, first_bad);
    report("f16 round trip exhaustive", bad == 0, d);
    std::snprintf(d, sizeof d, "legacy loses %d (the flushed subnormals)", legacy_bad);
    report("  control: legacy loses some", legacy_bad > 0, d);
  }

  // ---- NaN and infinity survive as such ----
  {
    const float inf = HUGE_VALF;
    const float nan = std::nanf("");
    const bool ok = cpi::f32_to_f16(inf) == 0x7C00 && cpi::f32_to_f16(-inf) == 0xFC00 &&
                    std::isinf(cpi::f16_to_f32(0x7C00)) && cpi::f16_to_f32(0x7C00) > 0 &&
                    std::isinf(cpi::f16_to_f32(0xFC00)) && cpi::f16_to_f32(0xFC00) < 0 &&
                    ((cpi::f32_to_f16(nan) >> 10) & 0x1F) == 0x1F &&
                    (cpi::f32_to_f16(nan) & 0x3FF) != 0 && std::isnan(cpi::f16_to_f32(0x7E00));
    report("inf and nan", ok);
  }

  // ---- rounding must be unbiased ----
  //
  // The point of the change: truncation always moves toward zero, so it shrinks magnitudes
  // systematically. Rounding's error should average out.
  //
  // Sampled POSITIVE-only on purpose. Over data symmetric about zero, truncation's bias cancels
  //, it pulls positives down and negatives up in equal measure, and this check would read as
  // "unbiased" for both converters while measuring nothing. (It did, on the first draft: legacy
  // scored +1.4e-06 against rounding's -1.0e-06.) Real tensors are not symmetric, which is why
  // the vision path's input pixels showed -1.5e-4 truncating against +5.8e-7 rounding.
  {
    double sum_new = 0.0, sum_legacy = 0.0;
    int n = 0;
    std::uint32_t seed = 12345u;
    for (int i = 0; i < 200000; ++i) {
      seed = seed * 1664525u + 1013904223u;
      const float v = 0.5f + static_cast<float>(seed >> 8) / 8388608.0f * 3.5f;  // [0.5, 4)
      sum_new += static_cast<double>(cpi::f16_to_f32(cpi::f32_to_f16(v)) - v);
      sum_legacy += static_cast<double>(legacy_f16_to_f32(legacy_f32_to_f16(v)) - v);
      ++n;
    }
    const double mean_new = sum_new / n, mean_legacy = sum_legacy / n;
    char d[128];
    std::snprintf(d, sizeof d, "mean signed err %+.3e", mean_new);
    report("rounding is unbiased", std::fabs(mean_new) < std::fabs(mean_legacy) / 50.0, d);
    std::snprintf(d, sizeof d, "legacy %+.3e, %.0fx worse", mean_legacy,
                  std::fabs(mean_legacy) / (std::fabs(mean_new) + 1e-30));
    report("  control: legacy is biased", std::fabs(mean_legacy) > 1e-5, d);
  }

  // ---- optional external fixture ----
  if (argc >= 3) {
    std::FILE* fv = std::fopen(argv[1], "r");
    std::FILE* fe = std::fopen(argv[2], "r");
    if (fv == nullptr || fe == nullptr) {
      report("fixture", false, "cannot open the given files");
    } else {
      char lv[128], le[128];
      int bad = 0, legacy_bad = 0, n = 0;
      while (std::fgets(lv, sizeof lv, fv) != nullptr && std::fgets(le, sizeof le, fe) != nullptr) {
        const float v = std::strtof(lv, nullptr);
        const auto want = static_cast<std::uint16_t>(std::strtoul(le, nullptr, 10));
        if (cpi::f32_to_f16(v) != want) ++bad;
        if (legacy_f32_to_f16(v) != want) ++legacy_bad;
        ++n;
      }
      char d[128];
      std::snprintf(d, sizeof d, "%d/%d wrong (legacy %d)", bad, n, legacy_bad);
      report("fixture vs numpy", bad == 0 && n > 0, d);
    }
    if (fv != nullptr) std::fclose(fv);
    if (fe != nullptr) std::fclose(fe);
  } else {
    std::printf("  %-28s no fixture given (pass vals.txt expect.txt to include it)\n", "fixture");
  }

  std::printf("[metal_fp16] %s\n", failures == 0 ? "ALL PASS" : "FAILURES");
  return failures == 0 ? 0 : 1;
}
